DAD-51 #Done
giusvale-dev/distributed_anomalies_detection pull request #3
Opened 2024-03-24 19:22 UTC by antoniociprani

2024-03-25 19:25 UTC, giusvale-dev commented on user-manager-ui/src/app/components/users/users.component.ts
> +    this.resp = this.userService.getUsers('https://dummyjson.com/users').subscribe({
Please insert the URL in the environment file, not here!

2024-03-25 19:26 UTC, giusvale-dev commented on user-manager-ui/src/app/services/user.service.ts
> +    return this.http.get('https://dummyjson.com/users/' + `${ id }`)
Insert the URL in the environment file

2024-03-25 19:27 UTC, giusvale-dev requested changes
Need changes before to approve.

2024-03-27 20:28 UTC, antoniociprani commented
Changes done

2024-03-29 22:16 UTC, giusvale-dev approved these changes
Thanks Antonio

2024-03-29 22:17 UTC, merged